# Generated by Django 3.0.5 on 2021-05-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('currency', models.TextField(max_length=100)),
                ('symbol', models.TextField(max_length=100)),
                ('centseparator', models.TextField(max_length=100)),
                ('millionseparator', models.TextField(max_length=100)),
                ('locale', models.TextField(max_length=100)),
                ('decimals', models.TextField(max_length=100)),
                ('displaysymbol', models.TextField(max_length=100)),
            ],
        ),
    ]
