# Generated by Django 3.0.5 on 2021-05-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='centseparator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='decimals',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='displaysymbol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='locale',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='millionseparator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
